### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by busyninja** [yassineaddi/BackdoorMan#1] opened 2016-12-13 10:35 UTC
Dear sirs,

Thanks a lot for making this tool, I think it will be very usefull.

I tryed on two of my web servers but it's not working, when using apis.  I've tryed to launch a scan with and without apis. With apis I always get same error:
`********* ~/BackdoorMan # ./BackdoorMan /var/www/****************/htdocs/
[*] Scanning: /var/www/******************/htdocs/
[*] Started: 2016-12-13 11:29:51.275150
Traceback (most recent call last):
  File "./BackdoorMan", line 603, in <module>
    Initialize(dest)
  File "./BackdoorMan", line 75, in __init__
    self.list()
  File "./BackdoorMan", line 98, in list
    self.PHPScan(file)
  File "./BackdoorMan", line 337, in PHPScan
    response = servicer.shellray()
  File "./BackdoorMan", line 432, in shellray
    data = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

Thanks in advance.

Kind regards.

**Comment by yassineaddi** [comment] 2016-12-13 11:29
Hello @busyninja 

It looks like the problem is that shellray has added a service limitation. After using it for a while I get also the same error, printing the `r.text` gave me the following message: limit exceeded

So, too bad they are starting doing that. Anyway, I think you will be able to use it again after 24 hours o maybe less.

I did a fix for this issue.

Thank you for using BackdoorMan, I hope it will be useful for you!

Best regards.
Yassine.

**Comment by busyninja** [comment] 2016-12-13 17:29
Thanks a lot, it works very well.

**Comment by yassineaddi** [comment] 2016-12-13 19:00
Glad to hear that, you're most welcome.

**Closed by yassineaddi** 2016-12-13 19:00 UTC
